services:
  - type: web
    name: pythonchecker
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGIN
        value: https://pythonchecker.onrender.com
    plan: free
